changelog:
  exclude:
    labels:
      - dependency
      - duplicate
      - question
      - wontfix
    authors:
      - linear-ci_comcast
      - renovate
  categories:
    - title: Features 🚀
      labels:
        - enhancement
        - feature
    - title: Fixes 🛠
      labels:
        - bug
        - fix
    - title: Other Changes 📦
      labels:
        - "*"
