changelog:
  exclude:
    labels:
      - duplicate
      - question
      - wontfix
    authors:
      - renovate
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
