version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - gocritic
    - godox
    - gosec
    - misspell
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - examples/*
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
